# Generated by Django 4.1.9 on 2023-06-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_musicians_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre edificio')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción edificio')),
                ('location', models.CharField(max_length=100, verbose_name='Ubicacion')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('type', models.CharField(default='office', max_length=100, verbose_name='tipo edificio')),
                ('capacity', models.IntegerField(default=100, verbose_name='Alojamiento')),
                ('space', models.FloatField(default=100, verbose_name='espacio')),
            ],
        ),
        migrations.DeleteModel(
            name='Musicians',
        ),
    ]
