# Generated by Django 4.1.9 on 2023-06-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_building_delete_musicians'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='price',
            field=models.FloatField(default=100, verbose_name='Precio'),
        ),
    ]
