# Generated by Django 4.1.9 on 2023-06-27 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_building_g_maps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='space',
            new_name='num_people',
        ),
        migrations.AddField(
            model_name='reservation',
            name='id_building',
            field=models.IntegerField(default=0, verbose_name='building'),
        ),
    ]
