# Generated by Django 4.1.9 on 2023-06-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_space_reservation_num_people_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='num_people',
            field=models.CharField(max_length=20, verbose_name='Ocupantes'),
        ),
    ]
