# Generated by Django 4.1.9 on 2023-06-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_usermodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='Ciudad'),
        ),
    ]
