# Generated by Django 4.1.9 on 2023-06-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_usermodel_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='id_user',
            field=models.PositiveIntegerField(default=0, verbose_name='usuario'),
        ),
    ]
