# Generated by Django 4.1.9 on 2023-06-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_reservation_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='clave',
            field=models.CharField(default='', max_length=20, verbose_name='clave'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='admin?'),
        ),
    ]
